name: CI

on:
  pull_request:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: true
      # https://hexdocs.pm/elixir/1.14.0/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
      matrix:
        include:
          - elixir: 1.11
            otp: 21.x
          - elixir: 1.11
            otp: 22.x
          - elixir: 1.11
            otp: 23.x

          - elixir: 1.12
            otp: 22.x
          - elixir: 1.12
            otp: 23.x
          - elixir: 1.12
            otp: 24.x

          - elixir: 1.13
            otp: 22.x
          - elixir: 1.13
            otp: 23.x
          - elixir: 1.13
            otp: 24.x
          - elixir: 1.13
            otp: 25.x

          - elixir: 1.14
            otp: 23.x
          - elixir: 1.14
            otp: 24.x
          - elixir: 1.14
            otp: 25.x

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get --only test
      - run: mix format --check-formatted
      - run: mix deps.get && mix deps.unlock --check-unused
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
      - run: mix test
